---
apiVersion: v1
kind: Secret
metadata:
  name: weshopify-db-config-secret
  labels: 
	secret: weshopify-db-config-secret
data:
  DB_USER_NAME_VALUE: cm9vdA==
  DB_PASSWORD_VALUE: cm9vdA==
type: Opaque
...
